### PR TITLE
Update Stripe library; Elixir version

### PR DESCRIPTION
**Pull request by joshsmith**
# What's in this PR?

Updates the Stripe library to use latest alpha branch. Also updates our version of Elixir.

### CODE REVIEW

**Review by rlueder — APPROVED** [review]
@JoshSmith first time I'm looking at stripity-stripe, I noticed the changes from "secret_key" to "api_key" and "platform_client_id" to "connect_client_id" just wondering why the change?

**Comment by joshsmith** [comment]
@rlueder just more consistent naming changes.

**Comment by rlueder** [comment]
ok, thanks. I asked mainly because it didn't match the docs under Configuration here: https://github.com/code-corps/stripity-stripe

**Comment by joshsmith** [comment]
@rlueder yeah, those are docs for `master`, but the real docs are on hex under `2.0.0-alpha.1`

**Pull request merged**
