### PR TITLE
run mix.deps before building the Docker image

### PR DESCRIPTION
**Pull request by SViccari**
Hi there!

First PR for this repo 😸  I'm eager to help resolve some of the issues I've encountered when trying to run this application locally with Docker and docker-compose. This PR is limited to Dockerfile changes as I'm still reading the docker-compose docs to identify the ideal way to use `volumes` (aka, mapping to include local file changes).

Why:
I ran into a number of errors when running docker-compose up and then
running the command 'docker-compose run test mix test'. The most common
error being 'could not compile dependency :dependency_name, "mix compile"
failed'.

This PR:
Copies the necessary mix files into the app directory and then fetches
all the dependencies.

Detailed error message referenced above:

```
==> arc
could not compile dependency :arc, "mix compile" failed. You can recompile this dependency with "mix deps.compile arc", update it with "mix deps.update arc" or clean it with "mix deps.clean arc"
==> code_corps
** (Mix) Failed to open Hex registry (file does not exist, run `mix hex.info` to fetch it)
```

### CODE REVIEW

**Comment by joshsmith** [comment]
@SViccari your tests are failing because we fixed something on forked PR builds. Fetch your `develop` branch from upstream and rebase and it should be fine.

I'll pull down and test once that's all good to go.

**Review by joshsmith — APPROVED** [review]
👍

**Comment by joshsmith** [comment]
@SViccari this looks great and combined with #314 looks like it will solve our most annoying and pressing issues. When you have the opportunity to rebase, we'll get this merged in ASAP.

Thanks so much!

**Comment by SViccari** [comment]
@JoshSmith branch has been rebased :) Did you find the time to pull this down and confirm it works locally for you?

**Comment by joshsmith** [comment]
@SViccari oh no! I just merged one thinking you hadn't rebased yet. 😢 

I hadn't pulled down, but trust given what I know that with @Fahrradflucht's and your change that this should fix my issues.

**Comment by SViccari** [comment]
@JoshSmith haha, no worries, I'll rebase again.

**Comment by joshsmith** [comment]
🙌 go team!

**Pull request merged**
