### PR TITLE
Add approved column to organizations

### PR DESCRIPTION
**Pull request by dleve123**
Making some progress towards #523

- Add an `approved` column to `organizations`
- Index `approved`

### CODE REVIEW

**Comment by joshsmith** [comment]
@dleve123 looks great! Can you add an index to the column since we'll also be scoping some requests to approved projects only?

Thanks!

**Comment by dleve123** [comment]
@JoshSmith will do! To be transparent about timeframe, I'm going to make these changes by next weekend.

**Comment by joshsmith** [comment]
@dleve123 no problem! I might submit a PR to your repo in the meantime, depending. If you have a moment to keep an eye out for that just in case, that would be helpful.

**Comment by dleve123** [comment]
@JoshSmith absolutely - will keep them 👀  peeled!

**Comment by joshsmith** [comment]
Hey @dleve123 never had a chance myself to circle back to this due to other things. Do you know when you might have a chance?

**Comment by dleve123** [comment]
@JoshSmith I took a brief look at CircleCI, and it looks like it is not rebuilding the commits. Assuming you can get CI to rebuild, this PR has been updated to include an index, and should be good to merge!

**Comment by joshsmith** [comment]
@dleve123 I have not had a chance to review yet in favor of the donations milestones. We will circle back soon, I promise.

**Comment by dleve123** [comment]
@JoshSmith - sounds good.

**Comment by joshsmith** [comment]
@dleve123 it looks like you can rebase and it will actually trigger a build now!

**Comment by dleve123** [comment]
@JoshSmith just rebased against `develop`

**Review by begedin — APPROVED** [review]
Looks good to go. I wouldn't even squash before merging, since the two commits are two distinct changes.

**Comment by dleve123** [comment]
@JoshSmith ping on this!

**Comment by joshsmith** [comment]
@dleve123 good to go! 🙌

**Comment by dleve123** [comment]
woo!

**Pull request merged**
