### PR TITLE
Added filter by code support to org invites

### PR DESCRIPTION
**Pull request by begedin**
Required for code-corps/code-corps-ember#1556 to work correctly.

I took the opportunity to implement a generalized approach for filtering, to which we can potentially switch a few other endpoints as well.

### CODE REVIEW

**Review by joshsmith — COMMENTED** [review]
What’s going on with the mix.lock?

**Comment by begedin** [comment]
Just to answer the question, that's what happens for me when I have to do a `mix deps.get` if someone else updated a package in another PR and it got merged to dev.

**Comment by joshsmith** [comment]
Are you sure you have the latest hex?

**Comment by begedin** [comment]
I thought I did, but apparently not. Updated, so hopefully it does not happen again.

**Pull request merged**
