### PR TITLE
Add unit test for CodeCorps.Helpers.CloudinaryUrl and RandomIconColor

### LINKED ISSUE #675: Add unit test for CodeCorps.Helpers.CloudinaryUrl and RandomIconColor
# Problem

As part of #672 we did not write unit tests for these. Would be good to add them.

### PR DESCRIPTION
**Pull request by YuriiZdyrko**
Added tests for:
lib/code_corps/helpers/cloudinary_url.ex
lib/code_corps/helpers/random_icon_color.ex

Moved `Cloudex` to configuration to allow testing.
## References
Closes #675

### CODE REVIEW

**Comment by begedin** [comment]
I like the unit testing, but there's still a piece missing which would allow the test and dev environments to run without the API keys. I'm working on getting that done in #695

Once that's merged, you can rebase from here and the tests should run. We can work on merging it in then.

**Comment by joshsmith** [comment]
@banzay that PR is merged now. Would you be able to rebase onto `develop` and see if that helps?

**Comment by YuriiZdyrko** [comment]
@JoshSmith 

> Would you be able to rebase onto develop and see if that helps?

 Done

**Comment by begedin** [comment]
This looks good to go. Thank you @banzay

**Review by begedin — APPROVED** [review]

**Comment by begedin** [comment]
Merging unsquashed because the two commits do different things.

**Comment by joshsmith** [comment]
Thanks @banzay :raised_hands:

**Pull request merged**
