### PR TITLE
Use json_payload strategy in controllers and eliminate use of build_payload

### PR DESCRIPTION
**Pull request by joshsmith**
@begedin This is a first attempt but do not understand how you had intended to handle relationships or the current user inside of the request.

### CODE REVIEW

**Comment by joshsmith** [comment]
@begedin the current implementation of `json_payload` is pretty rigid and I can't quite determine how we're supposed to be building relationships or dealing with complex relationship graphs when using this.

I think this, along with `load_and_authorize_changeset`, do require some documentation in the README and in the inline documentation, in addition to any refactoring that happens.

**Comment by begedin** [comment]
Me using the existing `@valid_attrs` in the categories controller test is probably a source of confusion. You should be able to build a payload with relationships, using 

``` Elixir
post = insert(:post)
user = insert(:user)
json_payload(:comment, post: post, user: user)
```

**Comment by joshsmith** [comment]
Going to hit pause on this pending #331.

**Comment by joshsmith** [comment]
Closing because I am not working on this right now.

**Pull request closed without merging**
