### PR TITLE
conform to credo style guides and add documentation explaining style …

### LINKED ISSUE #91: Either create our own style guide or reference existing one
Think we should use this as basis:

https://github.com/levionessa/elixir_style_guide

### PR DESCRIPTION
**Pull request by roryqueue**
…guidelines

Closes #91

### CODE REVIEW

**Comment by roryqueue** [comment]
Should I resolve the merge conflicts on my branch now?

**Comment by roryqueue** [comment]
In other words, should I merge code-corps-api/develop into roryqueue/develop first so the final merge can be automatic?

**Comment by joshsmith** [comment]
@roryqueue instead of merge, rebase will do this for you. This documentation should help some: https://github.com/code-corps/code-corps-ember/blob/develop/docs/SQUASHING.md

You'll go through a merge process when there are conflicts as each new commit in the rebase gets laid down.

Let me know if you want to pair on it and I'd be happy to help. We plan to do a video on this at some point.

**Comment by roryqueue** [comment]
^^ gotcha, the linked documentation is very helpful, should be good now here i think: https://github.com/code-corps/code-corps-api/pull/347

**Pull request closed without merging**
