### PR TITLE
Prevent swallowing of stripe errors

### LINKED ISSUE #540: Report errors from Stripe to Sentry
# Problem

Right now it looks like our errors on Stripe are being swallowed and not reported to Sentry. We need to ensure that the controller does render out the proper response but also sends the right error up to Sentry so that we can track these errors.

### PR DESCRIPTION
**Pull request by begedin**
# What's in this PR?

Fixes several identified places where errors due to Stripe API were being swallowed by explicitly rendering a 500 instead of letting them get raised.

I believe it's a good first step for letting Stripe errors get reported to sentry, but I'm not completely sure it's all we need.

## References
Fixes #540

### CODE REVIEW

**Comment by joshsmith** [comment]
I don't think this is all that we need. All that will happen in this case is that we'll get a match error, which is not sufficient in our logging to be able to identify what's happening, nor is it sufficient context to be able to send to Sentry. We'll know a match failed, but not know really much about why.

We may still need to match and then send specific Sentry events manually. Sentry will lack some automatic context in this case and I'm not sure whether the package will allow us to set the context manually.

**Comment by begedin** [comment]
This is what a typical mismatch error on a controller level looks like (and consequently, what gets reported by sentry:

```
[error] #PID<0.1117.0> running CodeCorps.Endpoint terminated
Server: api.localhost:4000 (http)
Request: POST /webhooks/stripe/connect
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in CodeCorps.StripeConnectEventsController.respond/2
        (code_corps) web/controllers/stripe_connect_events_controller.ex:30: CodeCorps.StripeConnectEventsController.respond(%Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{}, before_send: [#Function<1.82227598/1 in Plug.Logger.call/2>, #Function<0.131639940/1 in Phoenix.LiveReloader.before_send_inject_reloader/1>], body_params: %{"api_version" => "2016-07-06", "created" => 1326853478, "data" => %{"object" => %{"business_logo" => nil, "business_name" => "Code Corps", "business_url" => nil, "charges_enabled" => false, "country" => "US", "debit_negative_balances" => true, "decline_charge_on" => %{"avs_failure" => false, "cvc_failure" => true}, "default_currency" => "usd", "details_submitted" => true, "display_name" => nil, "email" => "test@stripe.com", "external_accounts" => %{"data" => [], "has_more" => false, "object" => "list", "total_count" => 0, "url" => "/v1/accounts/acct_17XohmBKl1F6IRFf/external_accounts"}, "id" => "acct_00000000000000", "legal_entity" => %{"additional_owners" => [], "address" => %{"city" => nil, "country" => "US", "line1" => nil, "line2" => nil, "postal_code" => nil, "state" => nil}, "business_name" => "Code Corps", "business_tax_id_provided" => false, "dob" => %{"day" => nil, "month" => nil, "year" => nil}, "first_name" => "Nikola", "last_name" => "Begedin", "personal_address" => %{"city" => nil, "country" => "US", "line1" => nil, "line2" => nil, "postal_code" => nil, "state" => nil}, "personal_id_number_provided" => false, "ssn_last_4_provided" => false, "type" => "sole_prop", "verification" => %{"details" => nil, "details_code" => nil, "document" => nil, "status" => "unverified"}}, "managed" => false, "object" => "account", "product_description" => "Code Corps accepts donations on the Code Corps platform in order to build and sustain open source software for public good. Donations usually happen once a month, although the frequency may vary.", "statement_descriptor" => "TEST", "support_email" => nil, "support_phone" => nil, "timezone" => "Europe/Zagreb", "tos_acceptance" => %{"date" => nil, "ip" => nil, "user_agent" => nil}, "transfer_schedule" => %{"delay_days" => 2, "interval" => "daily"}, "transfer_statement_descriptor" => nil, "transfers_enabled" => true, "verification" => %{"disabled_reason" => "fields_needed", "due_by" => 1481463077, "fields_needed" => ["legal_entity.verification.document"]}}, "previous_attributes" => %{"verification" => %{"due_by" => nil, "fields_needed" => []}}}, "id" => "evt_00000000000000", "livemode" => false, "object" => "event", "pending_webhooks" => 1, "request" => nil, "type" => "account.updated"}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "api.localhost", method: "POST", owner: #PID<0.1117.0>, params: %{"api_version" => "2016-07-06", "created" => 1326853478, "data" => %{"object" => %{"business_logo" => nil, "business_name" => "Code Corps", "business_url" => nil, "charges_enabled" => false, "country" => "US", "debit_negative_balances" => true, "decline_charge_on" => %{"avs_failure" => false, "cvc_failure" => true}, "default_currency" => "usd", "details_submitted" => true, "display_name" => nil, "email" => "test@stripe.com", "external_accounts" => %{"data" => [], "has_more" => false, "object" => "list", "total_count" => 0, "url" => "/v1/accounts/acct_17XohmBKl1F6IRFf/external_accounts"}, "id" => "acct_00000000000000", "legal_entity" => %{"additional_owners" => [], "address" => %{"city" => nil, "country" => "US", "line1" => nil, "line2" => nil, "postal_code" => nil, "state" => nil}, "business_name" => "Code Corps", "business_tax_id_provided" => false, "dob" => %{"day" => nil, "month" => nil, "year" => nil}, "first_name" => "Nikola", "last_name" => "Begedin", "personal_address" => %{"city" => nil, "country" => "US", "line1" => nil, "line2" => nil, "postal_code" => nil, "state" => nil}, "personal_id_number_provided" => false, "ssn_last_4_provided" => false, "type" => "sole_prop", "verification" => %{"details" => nil, "details_code" => nil, "document" => nil, "status" => "unverified"}}, "managed" => false, "object" => "account", "product_description" => "Code Corps accepts donations on the Code Corps platform in order to build and sustain open source software for public good. Donations usually happen once a month, although the frequency may vary.", "statement_descriptor" => "TEST", "support_email" => nil, "support_phone" => nil, "timezone" => "Europe/Zagreb", "tos_acceptance" => %{"date" => nil, "ip" => nil, "user_agent" => nil}, "transfer_schedule" => %{"delay_days" => 2, "interval" => "daily"}, "transfer_statement_descriptor" => nil, "transfers_enabled" => true, "verification" => %{"disabled_reason" => "fields_needed", "due_by" => 1481463077, "fields_needed" => ["legal_entity.verification.document"]}}, "previous_attributes" => %{"verification" => %{"due_by" => nil, "fields_needed" => []}}}, "id" => "evt_00000000000000", "livemode" => false, "object" => "event", "pending_webhooks" => 1, "request" => nil, "type" => "account.updated"}, path_info: ["webhooks", "stripe", "connect"], path_params: %{}, peer: {{127, 0, 0, 1}, 54723}, port: 4000, private: %{CodeCorps.Router => {[], %{}}, :phoenix_action => :create, :phoenix_controller => CodeCorps.StripeConnectEventsController, :phoenix_endpoint => CodeCorps.Endpoint, :phoenix_format => "json", :phoenix_layout => {CodeCorps.LayoutView, :app}, :phoenix_pipelines => [:stripe_webhooks], :phoenix_route => #Function<58.33575360/1 in CodeCorps.Router.match_route/4>, :phoenix_router => CodeCorps.Router, :phoenix_view => CodeCorps.StripeConnectEventsView, :plug_session_fetch => #Function<1.46198565/1 in Plug.Session.fetch_session/1>}, query_params: %{}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"host", "api.localhost:4000"}, {"connection", "keep-alive"}, {"content-length", "2854"}, {"postman-token", "d707f10c-83a6-a57a-8a56-fe57daed6e74"}, {"cache-control", "no-cache"}, {"origin", "chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop"}, {"user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"}, {"content-type", "application/json"}, {"accept", "*/*"}, {"accept-encoding", "gzip, deflate, br"}, {"accept-language", "en-US,en;q=0.8,hr;q=0.6,en-GB;q=0.4"}], request_path: "/webhooks/stripe/connect", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "70lf0lp728709ttahct6qdm3g1tiq4vv"}], scheme: :http, script_name: [], secret_key_base: "eMl0+Byu0Zv7q48thBu23ChBVFO1+sdLqoMI8yZoxEviF1K3C5uIohbDfvM9felL", state: :unset, status: nil}, {:error, :stripe_error})
        (code_corps) web/controllers/stripe_connect_events_controller.ex:1: CodeCorps.StripeConnectEventsController.action/2
        (code_corps) web/controllers/stripe_connect_events_controller.ex:1: CodeCorps.StripeConnectEventsController.phoenix_controller_pipeline/2
        (code_corps) lib/code_corps/endpoint.ex:1: CodeCorps.Endpoint.instrument/4
        (code_corps) lib/phoenix/router.ex:261: CodeCorps.Router.dispatch/2
        (code_corps) web/router.ex:1: CodeCorps.Router.do_call/2
        (code_corps) lib/plug/error_handler.ex:64: CodeCorps.Router.call/2
        (code_corps) lib/code_corps/endpoint.ex:1: CodeCorps.Endpoint.phoenix_pipeline/1
        (code_corps) lib/plug/debugger.ex:123: CodeCorps.Endpoint."call (overridable 3)"/2
        (code_corps) lib/code_corps/endpoint.ex:1: CodeCorps.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

I believe that for now, until we start getting esoteric errors, the information above is enough to fix an issue with our setup, or to start handling scenarios we did not foresee. The information sentry reports is

* where the error occurred
* which function was called (from which, we can determine which arguments it was supposed to get)
* which arguments the function was called with

What happens when such a mismatch occurs, after I removed the handlers in this PR is:

1. The client get's a 500 response
2. Sentry reports the error with all the information above.

What was happening before was

1. The client got the same 500 response
2. Sentry did nothing, because the error itself was swallowed

We could send more information, but I'm not really sure what else to send. It would have to be specific for each specific case where additional information would be useful and we don't really have those cases yet.

It's possible I'm missing something, so any advice would be welcome, but right now, I can't think of anything myself.

# There is a `sentry-elixir` bug

What I did find out while researching this was the following bug sentry has - https://github.com/getsentry/sentry-elixir/issues/96. Basically, if we hit an endpoint with parameters that are anything but a string, the default body scrubber will fail and sentry will report something completely useless, if at all.

We can circumvent it, for now, by specifying our own body scrubber, which I did and pushed into this PR, with a comment to remove it once the sentry bug is fixed.

I'm really not sure what else to do here.

**Comment by begedin** [comment]
@mitchellhenke was extremely quick and pushed a fix to sentry which deals with the above problem, so I removed my own fix and updated sentry to 2.0.2 instead

**Comment by mitchellhenke** [comment]
@begedin sorry about that, thanks again for the report :)

**Review by joshsmith — APPROVED** [review]

**Pull request merged**
