### PR TITLE
Refactor role controller test by adding helpers

### LINKED ISSUE #433: Refactor Role Controller Tests with helpers
# Problem

Adding helpers from api_case.ex to the tests for Role Controller.

## References

Progress on: #413

### PR DESCRIPTION
**Pull request by mackenziehicks**
# What's in this PR?

Added helpers from api_case.ex to the tests for Role Controller.

## References
Fixes #433 

Progress on: #413

### CODE REVIEW

**Comment by joshsmith** [comment]
The tests are failing here. I think maybe the pagination tests are non-deterministic.

**Comment by joshsmith** [comment]
@begedin this is the same thing we've seen before, right?

**Comment by begedin** [comment]
@JoshSmith Yes, looks like it. I guess it isn't fixed yet.

**Review by sbatson5 — COMMENTED** [review]
LGTM 👍 👏

**Review by joshsmith — APPROVED** [review]

**Pull request merged**
