### PR TITLE
Added a note to installation steps for windows users

### PR DESCRIPTION
**Pull request by rileytaylor**
# What's in this PR?

Simple fix, this adds a note to INSTALLING.md for windows users to work with docker through powershell.

### CODE REVIEW

**Comment by joshsmith** [comment]
I would make this a recommend and not a must, unless Docker's docs say otherwise.

**Comment by joshsmith** [comment]
@rileytaylor ping.

**Comment by rileytaylor** [comment]
@JoshSmith from what I can find in documentation there is nothing saying you have to, though it is generally what Docker uses for samples. I do know it was at a minimum highly recommended (that's where I'm recalling the requirement) at BUILD. I'm going to make it recommended and put a note that if there are odd issues to run PS as Admin.

**Review by joshsmith — APPROVED** [review]

**Comment by joshsmith** [comment]
LGTM!

**Pull request merged**
