### PR TITLE
Add tests for GitHub.Sync.installation_repositories_event/1

### LINKED ISSUE #1374: Write tests for GitHub.Sync.installation_repositories_event/1
# Problem

`GitHub.Sync.installation_repositories_event/1` is currently completely untested. Since we want to unit test it's individual elements to, it should suffice to test each possible outcome of the transaction performed by the tests, as defined by `GitHub.Sync.installation_repositories_event_outcome()`

## Subtasks

- [x] write tests for `{:ok, list(GithubRepo.t())}` outcome
- [x] write tests for `{:error, :unmatched_installation}` outcome
- [x] write tests for `{:error, :validation_error_on_syncing_repos, Changeset.t()}` outcome
- [ ] write tests for `{:error, :unexpected_transaction_outcome, any}` outcome

### PR DESCRIPTION
**Pull request by zacck-zz**
# What's in this PR?
This is a work in progress for test for the installation repositories even 

## References
Fixes #1374 

Progress on: #

### CODE REVIEW

**Comment by begedin** [comment]
@zacck If you rebase off of develop now, the build should pass

**Comment by zacck-zz** [comment]
@begedin  appears to still fail, However the CircleCI email says the other steps ran successfully

**Comment by zacck-zz** [comment]
Erm I think I broke something ...

**Comment by begedin** [comment]
hey @zacck 

The rebase broke. I managed to clean it up and rebase correctly, so it looks good to go now. 

Some general tips on rebasing PR-s

- It's easier if you have a smaller number of commits. Multiple smaller commits are fine when working on the PR, but when you feel it's ready to go, it's a good idea to clean up the commit list by merging individual commits into larger ones as they make sense. In this case, one big commit is good enough.
- Instead of using the rebase tool here, you'll be happier if you do a rebase through the console. The way you do that gis
  - `git checkout develop`
  - `git pull`
  - `git checkout your branch`
  - `git rebase -i origin/develop`

This gives you an interactive rebase where you can also squash your many tiny commits into bigger ones, etc.

We still prefer to use the UI here on the site for quick rebases and squashes, but generally, as soon as you get any conflicts with the base branch, you'll wanna do it from the command line.

**Comment by zacck-zz** [comment]
@begedin  thank you so much for the tips, will try to keep them in mind for the next time.

**Pull request merged**
