### PR TITLE
Resolve type errors flagged by Dialyzer

### LINKED ISSUE #1369: Fix dialyzer errors
# Problem

As of this writing, we have the following dialyzer errors:

```
lib/code_corps/emails/message_initiated_by_project_email.ex:14: Invalid type specification for function 'Elixir.CodeCorps.Emails.MessageInitiatedByProjectEmail':create/2. The success typing is (#{'__struct__':='Elixir.CodeCorps.Message', 'project':=#{'__struct__':='Elixir.CodeCorps.Project', 'title':=_, _=>_}, _=>_},#{'__meta__':=_, '__struct__':='Elixir.CodeCorps.Conversation', 'conversation_parts':=_, 'id':=_, 'inserted_at':=_, 'message':=_, 'message_id':=_, 'read_at':=_, 'status':=_, 'updated_at':=_, 'user':=#{'__struct__':='Elixir.CodeCorps.User', 'email':=_, 'first_name':=_, _=>_}, 'user_id':=_}) -> #{'__struct__':='Elixir.Bamboo.Email', 'assigns':=#{atom()=>_}, 'bcc':=_, 'cc':=_, 'from':=_, 'headers':=#{binary()=>binary()}, 'html_body':='nil' | binary(), 'private':=#{atom()=>_}, 'subject':='nil' | binary(), 'text_body':='nil' | binary(), 'to':=_}
lib/code_corps/policy/conversation_part.ex:41: Function authorize/2 has no local return
lib/code_corps/policy/conversation_part.ex:42: The pattern _conversation@1 = #{'__struct__':='Elixir.CodeCorps.Conversation'} can never match the type #{'__meta__':=_, '__struct__':='Elixir.CodeCorps.Message', 'author':=_, 'author_id':=_, 'body':=_, 'conversations':=_, 'id':=_, 'initiated_by':=_, 'inserted_at':=_, 'project':=_, 'project_id':=_, 'subject':=_, 'updated_at':=_}
lib/code_corps/policy/conversation_part.ex:54: Function 'conversation_target?'/2 will never be called
lib/code_corps_web/controllers/conversation_part_controller.ex:37: The pattern _conversation_part@1 = #{'__struct__':='Elixir.CodeCorps.ConversationPart'} can never match the type #{'__meta__':=_, '__struct__':='Elixir.CodeCorps.Conversation', 'conversation_parts':=_, 'id':=_, 'inserted_at':=_, 'message':=_, 'message_id':=_, 'read_at':=_, 'status':=_, 'updated_at':=_, 'user':=_, 'user_id':=_}
```

Didn't we add something that makes builds fail on these errors @asummers?

### PR DESCRIPTION
**Pull request by landongrindheim**
This PR fixes type specs that were being flagged by Dialyzer

## References
Closes #1369

### CODE REVIEW

**Comment by landongrindheim** [comment]
Not sure what to make of the build timing out. Is there anything I can do to resolve this?

**Comment by landongrindheim** [comment]
@begedin @joshsmith Any ideas as to what I can do to get the build passing?

**Comment by begedin** [comment]
Hey @landongrindheim Sorry for the delayed response. It looks like a build dependency has a bug. We're working on resolving it and it will hopefully get done today.

**Comment by begedin** [comment]
@landongrindheim If you rebase off of develop now, the build should pass

**Comment by landongrindheim** [comment]
@begedin rebased and pushed 😄

**Pull request merged**
