### PR TITLE
Style guide

### PR DESCRIPTION
**Pull request by roryqueue**

### CODE REVIEW

**Comment by joshsmith** [comment]
@roryqueue is this good to review now? Like ready to merge in case of approval?

**Comment by roryqueue** [comment]
yup

**Comment by roryqueue** [comment]
(should have zero behavior changes if all is well, passes all tests)

**Comment by joshsmith** [comment]
Got it. Have to go do this RSO certification test at Miramar but will review when I'm back from that.

**Comment by roryqueue** [comment]
Sweet, thanks man!

**Comment by roryqueue** [comment]
and good luck on your test 💯

**Comment by joshsmith** [comment]
Been a hectic day. Will have to review in morning.

**Comment by roryqueue** [comment]
No problem at all, I'm in no great rush :)

**Review by joshsmith — APPROVED** [review]
👍

**Comment by joshsmith** [comment]
@roryqueue awesome! Rebase, squash, and LGTM!

**Comment by joshsmith** [comment]
@roryqueue looks like the rebase pulled in more than you bargained for?

**Comment by roryqueue** [comment]
Indeed.. I've never really rebased commits before so I messed it up pretty royally. I'll take another crack at it today but if you have any advice that would be appreciated 🎱

**Comment by sbatson5** [comment]
@roryqueue I've bungled quite a few rebases in my day, haha. Did you rebase from master or develop?

Sometimes it is best to start fresh and just cherry pick your particular commits.

**Comment by roryqueue** [comment]
to develop. yeah, i wish I had kept a clean branch before trying it, but unfortunately I forgot to, so now I have to make sure I reset it cleanly and retry I think

**Comment by joshsmith** [comment]
@roryqueue yeah I think that it may actually even just be easier to copy/paste raw files from github in a new PR. I'd done that the first couple times I messed up a rebase.

**Comment by roryqueue** [comment]
Ah gotcha, yeah that totally works. I'll finish that by tomorrow, thanks!

**Comment by sbatson5** [comment]
@roryqueue since you changed so many files, `git cherry-pick <commit-sha>` is probably the easiest way to go: https://git-scm.com/docs/git-cherry-pick.

I.e. cut a new branch, then just do:
`git cherry-pick 596448eb74e07d8f558d07798ccadbfbe646725c` and it will add that exact commit with all the changes to your new branch.

If you squash your commits together beforehand, it should make it all pretty easy 👍

**Comment by roryqueue** [comment]
gotcha yeah that sounds good, finally learning some advanced git skills.

didn't do as well with overnight transportation as I thought last night, so may not have this figured out til tomorrow morning so I apologize for the delay, but checking in to confirm i'm still pushing on it.

**Comment by joshsmith** [comment]
Thanks @roryqueue, no worries!

**Comment by roryqueue** [comment]
I think i have resolved the git issues here: https://github.com/code-corps/code-corps-api/pull/344

**Pull request closed without merging**
