### PR TITLE
Not null constraints

### PR DESCRIPTION
**Pull request by mitchellhenke**
For #309

Unfortunately no way to add the constraint within Ecto's migration syntax that I could find.

### CODE REVIEW

**Comment by mitchellhenke** [comment]
hm, swear I ran the tests locally and they passed. will fix

**Comment by joshsmith** [comment]
@mitchellhenke just parked my car on way to meeting so sorry for abruptness, but I think this is what you're looking for https://hexdocs.pm/ecto/Ecto.Migration.html#modify/3

Should be able to just add `:null` under options mentioned there in docs.

**Comment by mitchellhenke** [comment]
@JoshSmith I tried this:

``` elixir
    alter table(:user_skills) do
      modify :user_id, references(:users), null: false
    end
```

but I get:

```
16:22:49.050 [info]  alter table user_skills
** (Postgrex.Error) ERROR (duplicate_object): constraint "user_skills_user_id_fkey" for relation "user_skills" already exists
```

**Comment by joshsmith** [comment]
@mitchellhenke you're right there I think. For the non-references you should be able to do it without the execute (no existing constraint). But this is simple enough that I'm okay with it. We execute more SQL than that elsewhere, believe me!

**Review by joshsmith — APPROVED** [review]

**Comment by joshsmith** [comment]
@mitchellhenke can you fetch upstream `develop` and rebase on that and squash into one commit? Then good to merge!

**Comment by mitchellhenke** [comment]
@JoshSmith updated!

**Pull request merged**
