### PR TITLE
[ROLE-SKILLS]: add index, filter, create, delete actions

### LINKED ISSUE #35: Add Role Skills API
Part of #26.

This can be split out into multiple issues to reflect the endpoints in the API docs: http://docs.codecorpsapidevelop.apiary.io/#reference/categories
- [ ] Create

### PR DESCRIPTION
**Pull request by joshsmith**
Closes #35.

### CODE REVIEW

**Comment by joshsmith** [comment]
Only thing different than user skill is the type is included in the relationship data and a few extra assertions.

Should maybe port these over to user skill. @begedin?

**Comment by begedin** [comment]
Not a bad idea to port. Looks good to go otherwise, so your choice if you wanna do it here or separately. 👍

**Comment by joshsmith** [comment]
Separately. Can you open an issue?

**Comment by begedin** [comment]
Created issue #81

**Pull request merged**
