### PR TITLE
GitHub update task

### LINKED ISSUE #803: When updating a task if it belongs to a GithubRepo update associated issue on github
# Problem

In the first iteration of github integration, a project can be assigned a repository on github, via a dropdown. Likewise, a task can then be assigned an issue on github.

If that is the case, when that task updates, the associated issue should update as well.

While we're handling this, we should extract task controller behavior into a separate module.

## Subtasks
- [ ] If it doesn't already exist, add `/lib/code_corps/task/task.ex` module, namespaced `CodeCorps.Task`
- [ ] Add `update/3` function to that module
   - Function accepts task, an attributes map and the current user
   - Function updates task, then updates associated github issue if necessary (using information from associated `GithubRepo` and the `github_issue_number` field.
   - Function returns `{:ok, task}` or `{:error, changeset}` or `{:error, _}`
   - If the current user is GitHub connected, the github API calls should be made on their behalf. If not, they should be made on the behalf of the default user provided by #800
- [ ] Modify `TaskController.update` to call the new module function
- [ ] Add tests for new service module/new function which assert these four cases:
  - Task with no github id is updated, `{:ok, updated_task}` was returned, no github api call was made
  - Task with github id was updated, `{:ok, updated_task}` was returned, a github call was made
  - There was a validation error
  - There was some other error

The existing controller tests can remain as is.

### PR DESCRIPTION
**Pull request by npendery**
# What's in this PR?

- [x] Add Github service `update_issue\3` function
- [ ] Add testing to task update function to account for github update

## References
Fixes #803

### CODE REVIEW

**Comment by begedin** [comment]
@npendery Same as with #805 , let me know how you feel about continuing this.

**Comment by begedin** [comment]
@npendery Hey Nick.

It's been a while, sadly, but building the basic infrastructure was complicated and required us to rethink how we approach a lot of things.

Still, it's done and it seems we've gotten to a point where we can get this working.

If you want to continue your work here, let me know. Otherwise, someone else will take over. What you did is very appreciated, though.

That being said, there are still a couple of things we need to figure out here

Apparently, the only documented way to access a github issue is through the `owner/repo/number` approach. 

There's this whole alternative github API which allows accessing issues, repos and users through their unique ids instead, which would be amazing, but it's undocumented, so we probably should not be using it.

With that in mind, it looks like `github_id` is not the field we should use to associate a task to a github issue.

That means it's more complicated than we hoped.

# In case you do want to continue, **some pointers**

The only way that I could think of to do it in an officially supported manner would be to have the task
- store a `github_issue_number` field
- have a `belongs_to :github_repo, CodeCorps.GithubRepo`

Both of these should be added and the `github_id` field should be removed

## When a task is created

- you should have a `github_repo_id` immediately, because, presumably, the user selected a github repo as they were creating the task on our site. We may do it differently at a later time, but this is the simplest approach I can think off
- use that id to retrieve a `GithubRepo` record from our database
- use the information in that record (`:github_account_login, :name`) to create an issue
- the creation request will return a payload containing a number, assign that to the `github_issue_number` field

- this all should be done in a transaction, if any part fails, no task should be created.

## When a task is updated

- the task you're updating might have a `github_repo` association and a `github_issue_number` field
- use those to also update the associated github issue through the github API
- this should be done in a transaction. if the local update fails, the github issue should not be updated and vice versa

**Comment by joshsmith** [comment]
@begedin is this PR still relevant after having #805 merged?

**Comment by begedin** [comment]
No, not at all. The `update` case has been covered by #805

@npendery Thank you for your work here, as well as #805. Unfortunately, the specs for the two issues you covered have changed so much from our initial idea, we had to take over, but your effort is still appreciated.

**Pull request closed without merging**
