### PR TITLE
Added a test for comment view

### PR DESCRIPTION
**Pull request by pt-arvind**
https://github.com/code-corps/code-corps-api/issues/242

### CODE REVIEW

**Comment by pt-arvind** [comment]
@JoshSmith  @begedin if you guys are OK with these changes, I will do the rebase, let me know when you get the chance!

**Comment by joshsmith** [comment]
Looks good to me, but will let @begedin review since he did initial review.

**Comment by joshsmith** [comment]
Actually no need for that, will just review myself. Was too tired to parse it well myself last night.

**Review by joshsmith — APPROVED** [review]
👍 LGTM!

**Comment by joshsmith** [comment]
@pt-arvind just rebase and squash. Let me know if you want to pair on that part. I would copy this branch over regardless just so you know you have it safe.

**Pull request merged**
